# Generated by Django 4.2.2 on 2023-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.TextField()),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('is_current', models.BooleanField()),
                ('address', models.TextField()),
                ('job_description', models.TextField()),
                ('company_name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
