# Generated by Django 4.2.2 on 2023-07-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_skill_name_alter_skill_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField()),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
            ],
        ),
    ]
