# Generated by Django 4.2.2 on 2023-07-11 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(default=datetime.date(2023, 7, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
