# Generated by Django 4.2.2 on 2023-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_created_on_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
